### ISSUE TITLE
Adding react client to infrastructure

### ISSUE THREAD

**Issue by pietrop** [bbc/digital-paper-edit-infrastructure#1]
**Is your feature request related to a problem? Please describe.**

Adding react client to infrastructure.

**Describe the solution you'd like**

[@bbc/digital-paper-edit-client](https://www.npmjs.com/package/@bbc/digital-paper-edit-client)

```
npm i @bbc/digital-paper-edit-client -save
```

**Describe alternatives you've considered**

serving static files in express imported from the npm module. 
[as described here](https://stackoverflow.com/questions/50913259/can-we-serve-static-files-in-a-node-module-for-a-server)

eg in express server 
```js
app.use("/", express.static(path.join(__dirname, '..', 'node_modules/@bbc/digital-paper-edit-client')));
```

**Additional context**

Leaving some notes re-adding react client to infrastructure, as just pushed the client to npm.

**Comment by emettely** [comment]
Marking as invalid as we moved to firebase
